### ISSUE TITLE
Translation: French

### ISSUE THREAD

**Issue by hersh-gupta** [hersh-gupta/covid-guidelines-app#3]
Starting from the English translation in [translations](https://github.com/hersh-gupta/covid-guidelines-app/tree/main/docs/translations/English.txt), translate the file, as is, into French.

**Comment by Laurie-38** [comment]
Hello, 
I try to do this !

**Comment by hersh-gupta** [comment]
Solved in latest updates to app. Thank you @Laurie-38!
