### ISSUE TITLE
Translation: Vietnamese

### ISSUE THREAD

**Issue by hersh-gupta** [hersh-gupta/covid-guidelines-app#6]
Starting from the English translation in [locales](https://github.com/hersh-gupta/covid-guidelines-app/blob/main/src/locales/en.json), translate the file, as is, into Vietnamese.

**Comment by putinpho** [comment]
There are some issues when merging the translation into the main, please be advised.

**Comment by hersh-gupta** [comment]
It looks like it's due to a [bug with npm](https://github.com/npm/cli/issues/3083). Thank you for your contribution, but I will be archiving this project.
